### PR TITLE
Bump to 3.10/3.11

### PR DESCRIPTION
**Pull request by bkerler**
Update module to gnuradio 3.10/3.11

### CODE REVIEW

**Comment by mhostetter** [comment]
Thanks for this!

It's been a while since I used GNU Radio. A couple questions:
- Are OOT modules for GR 3.10 and 3.11 interchangeable? I'm guessing this should get merged onto `maint-3.10` and we can advertise support for both versions?
- Do you know if the `maint-3.8` branch worked for GR 3.8 *and* 3.9?
- How did you make these changes? With a scripted conversion tool?

Again, thanks.

**Comment by mhostetter** [comment]
@bkerler did you happen to see my questions above?

**Comment by bkerler** [comment]
Hi, yes works with 3.10 and 3.11.
No, haven't tested the 3.8 version.
I didn't use any conversion script but did it all manually from scratch.

**Comment by mhostetter** [comment]
@bkerler sorry for the delay in getting around to this. I hesitated because my environments weren't set up to test this manually. I appreciate the contribution. 🙏

**Comment by bkerler** [comment]
No worries, thanks 👍

**Pull request merged**
